replicaCount: 2
image:
  repository: mariem631/portfolio-app-cicd-pipeline-frontend
  tag: "latest"  # Updated dynamically by CD pipeline
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 80